# Site settings
title: Mei Li's Blog
email: 
description: "仰望星空 脚踏实地"
baseurl: ""
url: "http://limei1221.github.io"
twitter_username: limei1221
github_username:  limei1221

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
